// Generated by scripts/generate-react-icons.mjs. Do not edit manually.
import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";

export const iconNames: readonly [
  "archive",
  "arrow-down",
  "arrow-left-filled",
  "arrow-left",
  "arrow-right-filled",
  "arrow-right",
  "arrow-turn-right",
  "arrow-up",
  "arrow-uturn",
  "arrows-swap",
  "attachment",
  "backpack",
  "balance-scale",
  "banknote-dollar",
  "banknote-refresh",
  "banknote-yen",
  "banknote",
  "bar-chart",
  "bell-off",
  "bell",
  "beta-circle",
  "beta",
  "book",
  "briefcase-business",
  "briefcase-chart",
  "briefcase-minus",
  "briefcase",
  "calendar-check",
  "calendar-ruble",
  "calendar",
  "camera-refresh",
  "camera",
  "card-details",
  "card-holder",
  "card-reader",
  "card-refresh-left",
  "card-refresh-right",
  "card-stack",
  "card-swap",
  "card-text",
  "cart",
  "catalog-search",
  "certificate",
  "charity",
  "chart-down",
  "chart-up",
  "chat-add",
  "chat-check",
  "chat-heart",
  "chat-help",
  "chat-more",
  "check",
  "chevron-center",
  "chevron-collapse",
  "chevron-diagonal",
  "chevron-down-filled",
  "chevron-down",
  "chevron-left",
  "chevron-mini",
  "chevron-right",
  "chevron-select",
  "chevron-up",
  "child",
  "circle-add",
  "circle-alert",
  "circle-arrow-right",
  "circle-chart",
  "circle-check",
  "circle-close",
  "circle-info",
  "circle-lightning",
  "circle-minus",
  "circle-moon",
  "circle-more",
  "circle-plane",
  "circle-question",
  "circle-zap",
  "circle",
  "click",
  "clock-filled",
  "clock",
  "coin-chart",
  "coin-down",
  "coin",
  "coins",
  "compass",
  "contact-card-alt",
  "contact-card",
  "copy",
  "counter-check",
  "counter-plus",
  "counter-time",
  "credit-card",
  "cross-small",
  "cross",
  "crown",
  "cup",
  "currency-dollar",
  "currency-euro",
  "currency-exchange-alt",
  "currency-exchange",
  "currency-ruble",
  "database",
  "dislike",
  "document-award",
  "document-chart",
  "document-details",
  "document-profile",
  "document-shield",
  "document-star",
  "document-text",
  "document",
  "edit",
  "equality",
  "exchange-in",
  "exchange-out",
  "eye-off",
  "eye",
  "file-check",
  "fire",
  "flag-banner",
  "flag",
  "folder-open",
  "folder",
  "gauge-high",
  "gauge-low",
  "gift",
  "globe",
  "gosuslugi",
  "grid-alt",
  "grid-featured",
  "grid",
  "hashtag",
  "heart",
  "home",
  "inbox",
  "ingot-stack",
  "ingot",
  "lightbulb",
  "like",
  "limit-100",
  "limit-50",
  "limit-60",
  "limit-full",
  "loader",
  "lock",
  "mail",
  "map-pin",
  "medical-cross",
  "menu",
  "message-off",
  "messages",
  "microphone-off",
  "microphone",
  "minus-small",
  "minus",
  "missed-call",
  "moon",
  "navigation",
  "notifications-off",
  "numbered-list",
  "pause",
  "payment-card",
  "payments",
  "person-add",
  "person-delay",
  "person-delete",
  "person-service",
  "person",
  "phone-add",
  "phone",
  "pie-chart",
  "pin-off",
  "pin",
  "plane",
  "play",
  "plus-small",
  "plus",
  "profile-card-alt",
  "profile-card",
  "profile-list-alt",
  "profile-list",
  "qr-smile",
  "qr",
  "refresh-left",
  "refresh-right",
  "refresh",
  "replay-circle",
  "safe-add",
  "safe-chart-card",
  "safe-chart",
  "safe-check",
  "safe-close",
  "safe-income",
  "safe-info",
  "safe-outcome",
  "safe-percent",
  "safe-toggle",
  "sber-logo",
  "screen-edit",
  "search-alt",
  "search",
  "settings",
  "share-screen",
  "share",
  "shield-chart",
  "shield-check",
  "shield-minus",
  "shield-smile",
  "shield",
  "sidebar",
  "sim-card",
  "sliders",
  "smartphone",
  "sound",
  "sparkle",
  "square-arrow-down",
  "square-bitcoin",
  "square-checkmark",
  "square-crypto",
  "square-pass",
  "square-percent",
  "stack",
  "star-smile",
  "star",
  "steering-wheel",
  "stop",
  "sun",
  "tag",
  "terminal-console",
  "text-badge",
  "text-cursor",
  "text-tool",
  "theme",
  "ticket-more",
  "trash",
  "umbrella",
  "unlocked",
  "users",
  "video-off",
  "video",
  "wallet-card",
  "wallet-check",
  "wallet-contactless",
  "wallet-refresh",
  "wallet",
  "washer",
  "wheel",
  "widget-edit",
  "zap"
];

export type IconName = (typeof iconNames)[number];
export type IconBaseProps = Omit<SVGProps<SVGSVGElement>, "children" | "name"> & {
  size?: number | string;
  title?: string;
};
export type IconProps = IconBaseProps & { name: IconName };
export type IconComponent = ForwardRefExoticComponent<
  IconBaseProps & RefAttributes<SVGSVGElement>
>;

export const Icon: ForwardRefExoticComponent<
  IconProps & RefAttributes<SVGSVGElement>
>;

export const IconArchive: IconComponent;
export const IconArrowDown: IconComponent;
export const IconArrowLeftFilled: IconComponent;
export const IconArrowLeft: IconComponent;
export const IconArrowRightFilled: IconComponent;
export const IconArrowRight: IconComponent;
export const IconArrowTurnRight: IconComponent;
export const IconArrowUp: IconComponent;
export const IconArrowUturn: IconComponent;
export const IconArrowsSwap: IconComponent;
export const IconAttachment: IconComponent;
export const IconBackpack: IconComponent;
export const IconBalanceScale: IconComponent;
export const IconBanknoteDollar: IconComponent;
export const IconBanknoteRefresh: IconComponent;
export const IconBanknoteYen: IconComponent;
export const IconBanknote: IconComponent;
export const IconBarChart: IconComponent;
export const IconBellOff: IconComponent;
export const IconBell: IconComponent;
export const IconBetaCircle: IconComponent;
export const IconBeta: IconComponent;
export const IconBook: IconComponent;
export const IconBriefcaseBusiness: IconComponent;
export const IconBriefcaseChart: IconComponent;
export const IconBriefcaseMinus: IconComponent;
export const IconBriefcase: IconComponent;
export const IconCalendarCheck: IconComponent;
export const IconCalendarRuble: IconComponent;
export const IconCalendar: IconComponent;
export const IconCameraRefresh: IconComponent;
export const IconCamera: IconComponent;
export const IconCardDetails: IconComponent;
export const IconCardHolder: IconComponent;
export const IconCardReader: IconComponent;
export const IconCardRefreshLeft: IconComponent;
export const IconCardRefreshRight: IconComponent;
export const IconCardStack: IconComponent;
export const IconCardSwap: IconComponent;
export const IconCardText: IconComponent;
export const IconCart: IconComponent;
export const IconCatalogSearch: IconComponent;
export const IconCertificate: IconComponent;
export const IconCharity: IconComponent;
export const IconChartDown: IconComponent;
export const IconChartUp: IconComponent;
export const IconChatAdd: IconComponent;
export const IconChatCheck: IconComponent;
export const IconChatHeart: IconComponent;
export const IconChatHelp: IconComponent;
export const IconChatMore: IconComponent;
export const IconCheck: IconComponent;
export const IconChevronCenter: IconComponent;
export const IconChevronCollapse: IconComponent;
export const IconChevronDiagonal: IconComponent;
export const IconChevronDownFilled: IconComponent;
export const IconChevronDown: IconComponent;
export const IconChevronLeft: IconComponent;
export const IconChevronMini: IconComponent;
export const IconChevronRight: IconComponent;
export const IconChevronSelect: IconComponent;
export const IconChevronUp: IconComponent;
export const IconChild: IconComponent;
export const IconCircleAdd: IconComponent;
export const IconCircleAlert: IconComponent;
export const IconCircleArrowRight: IconComponent;
export const IconCircleChart: IconComponent;
export const IconCircleCheck: IconComponent;
export const IconCircleClose: IconComponent;
export const IconCircleInfo: IconComponent;
export const IconCircleLightning: IconComponent;
export const IconCircleMinus: IconComponent;
export const IconCircleMoon: IconComponent;
export const IconCircleMore: IconComponent;
export const IconCirclePlane: IconComponent;
export const IconCircleQuestion: IconComponent;
export const IconCircleZap: IconComponent;
export const IconCircle: IconComponent;
export const IconClick: IconComponent;
export const IconClockFilled: IconComponent;
export const IconClock: IconComponent;
export const IconCoinChart: IconComponent;
export const IconCoinDown: IconComponent;
export const IconCoin: IconComponent;
export const IconCoins: IconComponent;
export const IconCompass: IconComponent;
export const IconContactCardAlt: IconComponent;
export const IconContactCard: IconComponent;
export const IconCopy: IconComponent;
export const IconCounterCheck: IconComponent;
export const IconCounterPlus: IconComponent;
export const IconCounterTime: IconComponent;
export const IconCreditCard: IconComponent;
export const IconCrossSmall: IconComponent;
export const IconCross: IconComponent;
export const IconCrown: IconComponent;
export const IconCup: IconComponent;
export const IconCurrencyDollar: IconComponent;
export const IconCurrencyEuro: IconComponent;
export const IconCurrencyExchangeAlt: IconComponent;
export const IconCurrencyExchange: IconComponent;
export const IconCurrencyRuble: IconComponent;
export const IconDatabase: IconComponent;
export const IconDislike: IconComponent;
export const IconDocumentAward: IconComponent;
export const IconDocumentChart: IconComponent;
export const IconDocumentDetails: IconComponent;
export const IconDocumentProfile: IconComponent;
export const IconDocumentShield: IconComponent;
export const IconDocumentStar: IconComponent;
export const IconDocumentText: IconComponent;
export const IconDocument: IconComponent;
export const IconEdit: IconComponent;
export const IconEquality: IconComponent;
export const IconExchangeIn: IconComponent;
export const IconExchangeOut: IconComponent;
export const IconEyeOff: IconComponent;
export const IconEye: IconComponent;
export const IconFileCheck: IconComponent;
export const IconFire: IconComponent;
export const IconFlagBanner: IconComponent;
export const IconFlag: IconComponent;
export const IconFolderOpen: IconComponent;
export const IconFolder: IconComponent;
export const IconGaugeHigh: IconComponent;
export const IconGaugeLow: IconComponent;
export const IconGift: IconComponent;
export const IconGlobe: IconComponent;
export const IconGosuslugi: IconComponent;
export const IconGridAlt: IconComponent;
export const IconGridFeatured: IconComponent;
export const IconGrid: IconComponent;
export const IconHashtag: IconComponent;
export const IconHeart: IconComponent;
export const IconHome: IconComponent;
export const IconInbox: IconComponent;
export const IconIngotStack: IconComponent;
export const IconIngot: IconComponent;
export const IconLightbulb: IconComponent;
export const IconLike: IconComponent;
export const IconLimit100: IconComponent;
export const IconLimit50: IconComponent;
export const IconLimit60: IconComponent;
export const IconLimitFull: IconComponent;
export const IconLoader: IconComponent;
export const IconLock: IconComponent;
export const IconMail: IconComponent;
export const IconMapPin: IconComponent;
export const IconMedicalCross: IconComponent;
export const IconMenu: IconComponent;
export const IconMessageOff: IconComponent;
export const IconMessages: IconComponent;
export const IconMicrophoneOff: IconComponent;
export const IconMicrophone: IconComponent;
export const IconMinusSmall: IconComponent;
export const IconMinus: IconComponent;
export const IconMissedCall: IconComponent;
export const IconMoon: IconComponent;
export const IconNavigation: IconComponent;
export const IconNotificationsOff: IconComponent;
export const IconNumberedList: IconComponent;
export const IconPause: IconComponent;
export const IconPaymentCard: IconComponent;
export const IconPayments: IconComponent;
export const IconPersonAdd: IconComponent;
export const IconPersonDelay: IconComponent;
export const IconPersonDelete: IconComponent;
export const IconPersonService: IconComponent;
export const IconPerson: IconComponent;
export const IconPhoneAdd: IconComponent;
export const IconPhone: IconComponent;
export const IconPieChart: IconComponent;
export const IconPinOff: IconComponent;
export const IconPin: IconComponent;
export const IconPlane: IconComponent;
export const IconPlay: IconComponent;
export const IconPlusSmall: IconComponent;
export const IconPlus: IconComponent;
export const IconProfileCardAlt: IconComponent;
export const IconProfileCard: IconComponent;
export const IconProfileListAlt: IconComponent;
export const IconProfileList: IconComponent;
export const IconQrSmile: IconComponent;
export const IconQr: IconComponent;
export const IconRefreshLeft: IconComponent;
export const IconRefreshRight: IconComponent;
export const IconRefresh: IconComponent;
export const IconReplayCircle: IconComponent;
export const IconSafeAdd: IconComponent;
export const IconSafeChartCard: IconComponent;
export const IconSafeChart: IconComponent;
export const IconSafeCheck: IconComponent;
export const IconSafeClose: IconComponent;
export const IconSafeIncome: IconComponent;
export const IconSafeInfo: IconComponent;
export const IconSafeOutcome: IconComponent;
export const IconSafePercent: IconComponent;
export const IconSafeToggle: IconComponent;
export const IconSberLogo: IconComponent;
export const IconScreenEdit: IconComponent;
export const IconSearchAlt: IconComponent;
export const IconSearch: IconComponent;
export const IconSettings: IconComponent;
export const IconShareScreen: IconComponent;
export const IconShare: IconComponent;
export const IconShieldChart: IconComponent;
export const IconShieldCheck: IconComponent;
export const IconShieldMinus: IconComponent;
export const IconShieldSmile: IconComponent;
export const IconShield: IconComponent;
export const IconSidebar: IconComponent;
export const IconSimCard: IconComponent;
export const IconSliders: IconComponent;
export const IconSmartphone: IconComponent;
export const IconSound: IconComponent;
export const IconSparkle: IconComponent;
export const IconSquareArrowDown: IconComponent;
export const IconSquareBitcoin: IconComponent;
export const IconSquareCheckmark: IconComponent;
export const IconSquareCrypto: IconComponent;
export const IconSquarePass: IconComponent;
export const IconSquarePercent: IconComponent;
export const IconStack: IconComponent;
export const IconStarSmile: IconComponent;
export const IconStar: IconComponent;
export const IconSteeringWheel: IconComponent;
export const IconStop: IconComponent;
export const IconSun: IconComponent;
export const IconTag: IconComponent;
export const IconTerminalConsole: IconComponent;
export const IconTextBadge: IconComponent;
export const IconTextCursor: IconComponent;
export const IconTextTool: IconComponent;
export const IconTheme: IconComponent;
export const IconTicketMore: IconComponent;
export const IconTrash: IconComponent;
export const IconUmbrella: IconComponent;
export const IconUnlocked: IconComponent;
export const IconUsers: IconComponent;
export const IconVideoOff: IconComponent;
export const IconVideo: IconComponent;
export const IconWalletCard: IconComponent;
export const IconWalletCheck: IconComponent;
export const IconWalletContactless: IconComponent;
export const IconWalletRefresh: IconComponent;
export const IconWallet: IconComponent;
export const IconWasher: IconComponent;
export const IconWheel: IconComponent;
export const IconWidgetEdit: IconComponent;
export const IconZap: IconComponent;

export const iconComponents: Readonly<Record<IconName, IconComponent>>;
export function getIconComponent(name: IconName): IconComponent;
export function getIconComponent(name: string): IconComponent | undefined;
